---

services:
  mailcatcher:
    enabled: false
    version: latest
    ram: 256M
    service_name: Mailcatcher (fake SMTP)
    service_url: http://{} (works also in https)
    service_extra_ports: [25]
  maildev:
    enabled: false
    version: latest
    ram: 256M
    service_name: Maildev (Fake SMTP)
    service_url: http://{} (works also in https)
    service_extra_ports: [25]
  mailhog:
    enabled: false
    version: latest
    ram: 256M
    service_name: MailHog (Fake SMTP)
    service_url: http://{} (works also in https)
    service_extra_ports: [1025]
