version: "3.8"

services:
  mailcatcher:
    image: tophfr/mailcatcher:${DOCKER_MAILCATCHER_VERSION}
    mem_limit: ${DOCKER_MAILCATCHER_RAM}
    container_name: ${COMPOSE_PROJECT_NAME}_mailcatcher
    hostname: ${COMPOSE_PROJECT_NAME}_mailcatcher
    networks: [stakkr]
    labels:
      traefik.enable: "true"
      traefik.http.routers.mailcatcher.tls: "true"
      traefik.http.routers.mailcatcher.rule: "Host(`mailcatcher.${COMPOSE_PROJECT_NAME}.${PROXY_DOMAIN}`)"
      traefik.http.services.mailcatcher.loadbalancer.server.port: 80
