version: "3.8"

services:
  mailhog:
    image: mailhog/mailhog:${DOCKER_MAILHOG_VERSION}
    mem_limit: ${DOCKER_MAILHOG_RAM}
    container_name: ${COMPOSE_PROJECT_NAME}_mailhog
    hostname: ${COMPOSE_PROJECT_NAME}_mailhog
    networks: [stakkr]
    labels:
      traefik.enable: "true"
      traefik.http.routers.mailhog.tls: "true"
      traefik.http.routers.mailhog.rule: "Host(`mailhog.${COMPOSE_PROJECT_NAME}.${PROXY_DOMAIN}`)"
      traefik.http.services.mailhog.loadbalancer.server.port: 8025
