version: '2.2'

services:
    maildev:
        image: djfarrelly/maildev:${DOCKER_MAILDEV_VERSION}
        mem_limit: ${DOCKER_MAILDEV_RAM}
        container_name: ${COMPOSE_PROJECT_NAME}_maildev
        hostname: ${COMPOSE_PROJECT_NAME}_maildev
        networks: [stakkr]
        labels:
            - traefik.frontend.rule=Host:maildev.${COMPOSE_PROJECT_NAME}.${PROXY_DOMAIN}
            - traefik.port=80 # because maildev exposes more than one port
